// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dropdown from "stimulus-dropdown"
application.register("dropdown", Dropdown)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import RangeSliderController from "./range_slider_controller.js"
application.register("range-slider", RangeSliderController)

import FlashcardCategoryController from "./flashcard_category_controller.js"
application.register("flashcard-category", FlashcardCategoryController)
